@vehicle_id={{list_vehicles.response.body.data[0].id}}

# @name create_vehicle
POST {{baseUrlDev}}/vehicles HTTP/1.1
Content-Type: application/json

{
    "brand": "Brand",
    "plate": "ttt-1663",
    "color": "preto"
}

################################################################################
# @name list_vehicles
GET {{baseUrlDev}}/vehicles?page=1&per_page=20&color=pre&brand=br&plate=ttt HTTP/1.1

################################################################################
# @name list_vehicle
GET {{baseUrlDev}}/vehicles/{{vehicle_id}} HTTP/1.1

################################################################################
# @name update_vehicle
PATCH  {{baseUrlDev}}/vehicles/{{vehicle_id}} HTTP/1.1
Content-Type: application/json

{
    "color": "black",
    "brand": "Marca edited",
    "plate": "ttt-1661"
}

################################################################################
# @name delete_vehicle
DELETE {{baseUrlDev}}/vehicles/{{vehicle_id}} HTTP/1.1